### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by guicho271828** [coleslaw-org/coleslaw#182]
if there is any demand.

**Comment by shukryzablah** [comment]
@guicho271828 What did you have in mind for this? I currently use coleslaw for my gitlab pages site.

**Comment by shukryzablah** [comment]
For anyone interested, this is the a very minimal example of a `.gitlab-ci.yml` that would allow you to get your coleslaw site hosted in Gitlab Pages. 

```yaml
image:
  name: fukamachi/sbcl:2.0.9-debian
  entrypoint: [""]

pages:
  script:
    - apt-get update
    - apt-get --yes install rsync
    - ros install coleslaw-cli
    - coleslaw stage
  artifacts:
    paths:
      - public
```

An example like this should be enough for someone to get up and running. It's different than github pages, so it doesn't really make sense to create a plugin for it.
